repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.270
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]

  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        language_version: python3
        args: [ --fast ]



fail_fast: true
